import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import Header from "./_partials/Header/";
import Footer from "./_partials/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "To-do List app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
